spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    http:
      path: /spectre-api/graphql
  session:
    jdbc:
      initialize-schema: always
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  application:
    version: @version@
server:
  error:
    path: /spectre-api/error
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

