spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: UTF-8
      force-response: true
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    http:
      path: /spectre-api/graphql
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true
  application:
    version: @version@
  web:
    error:
      path: /spectre-api/error
#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

