name: Spectre
services:
  web:
    environment:
      SPECTRE_HOME: '/home/spectre/data'
    ports:
      - "80:8080"
    volumes:
      - ./application.yaml:/home/spectre/application.yaml
      - ./data:/home/spectre/data
      - ./logs:/home/spectre/logs
    working_dir: /home/spectre
    image: public.ecr.aws/b9z8l9n7/vudsen/spectre:${SPECTRE_VERSION}
    command:
      - java
      - -Xmx1g
      - -jar
      - spectre.jar