spring:
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  datasource:
    url: jdbc:sqlite:identifier-integration-test.sqlite
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
  application:
    version: @version@
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    http:
      path: /spectre-api/graphql
logging:
  level:
    io.github.vudsen.spectre.core.service.impl.DefaultArthasExecutionService: debug
